# Default values for liquid-http.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: harbor.gladiators.dev/library
  name: liquid-http
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: 
  dapr.io/enabled: "true"
  dapr.io/app-id: "liquid-http"
  dapr.io/app-port: "80"

podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

resources: 
  limits:
    memory: 128Mi

livenessProbe:
  httpGet:
    path: /healtz
    port: http
readinessProbe:
  httpGet:
    path: /healtz
    port: http

volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# Additional volumeMounts on the output Deployment definition.
volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

nodeSelector: {}

tolerations: []

affinity: {}

ingress:
  enabled: true
  className: traefik
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: liquid.gladiators.dev
      paths:
        - path: /
          pathType: ImplementationSpecific
